name: Deploy development app
on:
  pull_request:
    branches:
      - dev
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Build for development env
      run: |
          ng build --configuration=development
    - name: Deploy Angular app using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY_ED25519 }}
        port: ${{ secrets.PORT }}
        source: "dist"
        target: "var/www/html"
        script: sh deploy-Angular.sh
