name: Deploy development app
on:
  pull_request:
    branches:
      - dev
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Deploy Angular app using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY_ED25519 }}
        port: ${{ secrets.PORT }}
        source: "*"
        target: "root/ftmAngularClient"
        script: sh deploy-Angular.sh ${{ steps.extract_branch.outputs.branch }}
