name: GitHub Deployment
on:
  push:
    branches: [ "main" ]
  workflow_run:
    workflows: [ "FTM-client-Angular CI/CD" ]
    types:
      - completed
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # Check out the project source code
        uses: actions/checkout@v3

      - name: Set up node.js
        uses: actions/setup-node@v3.3.0
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:prod

      - name: Create 404.html
        run: cp dist/Follow-the-money-Client/index.html dist/Follow-the-money-Client/404.html

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: dist/Follow-the-money-Client/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
