name: CI/CD

on: 
  push:
  pull_request:
    branches:
      - dev

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Check out the project source code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: |
          npm ci

      - name: Build
        if: github.event_name != 'pull_request'
        run: |
          npm run build:prod
          
      - name: Build dev
        if: github.event_name == 'pull_request'
        run: npm run build:dev

      - name: Lint
        run: |
          npm run lint

      - name: Test
        run: |
          npm run test -- --prod

      - name: Create 404.html
        if: github.ref == 'refs/heads/main'
        run: cp dist/Follow-the-money-Client/index.html dist/Follow-the-money-Client/404.html

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: dist/Follow-the-money-Client/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Deploy dist to mikr.us
        if: github.event_name == 'pull_request'
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.KEY_ED25519 }}
          port: ${{ secrets.PORT }}
          local: dist
          remote: ftmAngularClient
      
      - name: Run website on mikr.us
        if: github.event_name == 'pull_request'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY_ED25519 }}
          port: ${{ secrets.PORT }}
          script: sh deploy-Angular.sh
        
      
